CDH-79829: IMPALA-8408: Failure to load metadata for .deflate compressed text files
This is a partial backport of IMPALA-6941 (load more text scanner
compression plugins), which fixes the bug described in IMPALA-8408. The
bug causes several issues when users attempted to query tables that
contain files with unsupported compression formats (e.g. .deflate text
files). These issues include:

* The query itself would hang
* The impalad processing the unsupported files would throw an exception
when updating the ImpaladCatalog and enter a continous loop where they
would keep on requesting a prioritized load of a table that cannot be
applied to the ImpaladCatalog
* The actual Impala sessions would not get closed

This patch only backports the part of IMPALA-6941 which fixes the bug
described in IMPALA-8408. This change fixes the issue by removing the
isFileCompressionTypeSupported check in HdfsPartition, and instead lets
the scanners throw an exception for unsupported compression types. This
is consistent with the behavior post IMPALA-6941 where an attempt to
read a DEFLATE compressed text file would return the following error:

ERROR: Scanner plugin 'DEFLATE' is not one of the enabled plugins: 'LZO'

Now when users attempt to query DEFLATE compressed text files, they will
get the following error:

WARNINGS: Unsupported compression type DEFLATE for file
hdfs://localhost:20500/test-warehouse/test_deflate/test.deflate

This was tested on a mini cluster using the following test:

> create table test_deflate (id int) row format delimited fields terminated by ',';
> load data inpath '/tmp/test.deflate' into table test_deflate;
> select * from test_deflate;

WARNINGS: Unsupported compression type DEFLATE for file
hdfs: //localhost:20500/test-warehouse/test_deflate/test.deflate

Change-Id: I3c477beaf47f90fd244be9fef8a9d0ad4b60dfdd
Reviewed-on: https://gerrit.sjc.cloudera.com/c/Impala/+/46230
Reviewed-by: Tim Armstrong <tarmstrong@cloudera.com>
Tested-by: Sahil Takiar <stakiar@cloudera.com>