Remove spurious Boost warnings on compilation errors
Compilation errors can spuriously print warnings from Boost where the
filesystem module is used, like:

‘boost::system::posix_category’ defined but not used

Defining BOOST_SYSTEM_NO_DEPRECATED removes those warnings, which arise
from Boost maintaining deprecated names for error codes that have moved
namespaces during the shift to C++11 (see
http://www.boost.org/doc/libs/1_61_0/boost/system/error_code.hpp and
http://www.boost.org/doc/libs/1_61_0/libs/system/doc/reference.html).

We're not using the old names, so it's ok to remove them.

Change-Id: Ib84d8a9958469fb22b0af4907958917a65e8290f
Reviewed-on: http://gerrit.cloudera.org:8080/4564
Reviewed-by: Tim Armstrong <tarmstrong@cloudera.com>
Tested-by: Internal Jenkins