IMPALA-7360: sequence scanners sometimes skip blocks
The handling of sync markers after processing a block was broken - eos_
was set if the sync marker straddles the boundary. The expected
behaviour (documented by comments) in this case is that the current
scanner should process the next block, if there is one.

If you look at the logic before the IMPALA-3905 change in commit
931bf49cd90e496df6bf260ae668ec6944f0016c, it split the checking
of eosr() and eof() similar to this patch.

Testing:
Add regression tests that scans a large table with a variety of
different scan range lengths, with some randomisation to exercise
different edge cases. This reliably triggered the bug.

Backport notes: since Kudu does not implement DECIMAL types in
cdh6.0.x, and Kudu is not a sequence-based file format anyway,
query_tests/test_scanners.py excludes Kudu tables from the added
tests in tpch-scan-range-lengths.test.

Change-Id: I49a70a4925b0271204b8eea4f980299d7654805a
Reviewed-on: http://gerrit.cloudera.org:8080/11062
Reviewed-by: Michael Ho <kwho@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
(cherry picked from commit 717e51e9318a6ca477c0386aa3636868a7334d00)
Reviewed-on: https://gerrit.sjc.cloudera.com/37043
Tested-by: Laszlo Gaal <laszlo.gaal@cloudera.com>
Reviewed-by: Laszlo Gaal <laszlo.gaal@cloudera.com>