IMPALA-8173: Fix KeyError in run-workload.py
A recent change (IMPALA-7694) causes run-workload.py to fail with a
KeyError due to trying to construct an ImpalaBeeswaxResult without a
query id.

This patch fixes that issue and two related issues:
- This problem was not caught by automated testing even though we run
  run-workload.py in run-all-tests.sh because of an issue where
  queries that fail to produce results are silently ignored.
- Fixes an issue where queries that fail to produce results would
  confusingly produce the error:
  'NoneType' object has no attribute 'time_taken'

Testing:
- Ran run-workload.py locally and demonstrated that it works now.
- Ran run-all-tests.sh locally and demonstrated that it fails now when
  the KeyError issue isn't fixed.

Change-Id: I5b8a3c3dd7499335b9290d5667c194e8c0eabd12
Reviewed-on: http://gerrit.cloudera.org:8080/12397
Reviewed-by: Thomas Marshall <thomasmarshall@cmu.edu>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/49245
Tested-by: Jenkins User <jenkins@cloudera.com>
Reviewed-by: Laszlo Gaal <laszlo.gaal@cloudera.com>
Reviewed-by: Thomas Tauber-Marshall <tmarshall@cloudera.com>
Tested-by: Laszlo Gaal <laszlo.gaal@cloudera.com>
CDH-Build: Laszlo Gaal <laszlo.gaal@cloudera.com>
Quasar-L0: Laszlo Gaal <laszlo.gaal@cloudera.com>