IMPALA-7423: NoSuchMethodError when starting Sentry
The issue that is caused by the classpath ordering because of two
conflicting sentry-provider JARs:
- sentry-provider-db-2.0.0-cdh6.x-SNAPSHOT.jar
- sentry-provider-db-2.0.0-cdh6.x-SNAPSHOT-sh.jar (uses shaded Sentry
  Thrift)
This patch fixes the issue by removing sentry-provider-db:2.0.0:sh from
FE dependencies.

Testing:
- Ran a clean build and was able to start Sentry

Change-Id: Ie6cdfd184e06009a8d582499b2f6fd3011de6d5a
Reviewed-on: http://gerrit.cloudera.org:8080/11187
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>