IMPALA-6220: Revert "IMPALA-6128: Spill-to-disk Encryption(AES-CFB + SHA256) is slow"
Compilation failed on some platforms as ‘EVP_aes_256_ctr’ not declared in openssl-util.cc.
Reverting the change to unbreak the builds for now.

This reverts commit fb4c3b01240d8f65fc2c45bf27b668ae9b1fa5d2.

Change-Id: Id31d5fcfec5c6d777d4acee5c1be2d4fc4605efb
Reviewed-on: http://gerrit.cloudera.org:8080/8597
Reviewed-by: Xianda Ke <kexianda@gmail.com>
Reviewed-by: Tim Armstrong <tarmstrong@cloudera.com>
Tested-by: Michael Ho <kwho@cloudera.com>